/*
    SPDX-License-Identifier: GPL-3.0-or-later

    Installed by plasma-login-blur-slider; regenerated by
    "plasma-login-blur-slider sync". Do not edit.

    The stock wallpaper plugin has no configuration page of its own, so this
    one only carries the LoginBlurIntensity setting and, in the Login Screen
    settings, its slider.
*/

import QtQuick
import "plmblur" as PlmBlur

Item {
    id: plasmaLoginBlurWrapper

    // Set by the hosting settings page.
    property var configDialog

    property int cfg_LoginBlurIntensity: 100
    property int cfg_LoginBlurIntensityDefault: 100
    // Diagnostics switch ("plasma-login-blur-slider debug on"); no UI.
    property bool cfg_LoginBlurDebug: false
    property bool cfg_LoginBlurDebugDefault: false

    readonly property QtObject plasmaLoginBlurConfig: PlmBlur.LoginBlurConfig {
        configRoot: plasmaLoginBlurWrapper
        dialog: typeof configDialog !== "undefined" ? configDialog : null
        formLayout: (typeof appearanceRoot !== "undefined" && appearanceRoot && appearanceRoot.parentLayout)
            ? appearanceRoot.parentLayout : null
    }
}
