/*
    SPDX-License-Identifier: GPL-3.0-or-later

    Installed by plasma-login-blur-slider; regenerated by
    "plasma-login-blur-slider sync". Do not edit.

    The stock wallpaper plugin has no configuration page of its own, so this
    one only carries the LoginBlurIntensity setting and, in the Login Screen
    settings, its slider.
*/

import QtQuick
import "plmblur" as PlmBlur

Item {
    id: plasmaLoginBlurWrapper

    property int cfg_LoginBlurIntensity: 100
    property int cfg_LoginBlurIntensityDefault: 100

    readonly property QtObject plasmaLoginBlurConfig: PlmBlur.LoginBlurConfig {
        configRoot: plasmaLoginBlurWrapper
        dialog: typeof configDialog !== "undefined" ? configDialog : null
        formLayout: (typeof appearanceRoot !== "undefined" && appearanceRoot && appearanceRoot.parentLayout)
            ? appearanceRoot.parentLayout : null
    }
}
