/*
    SPDX-License-Identifier: GPL-3.0-or-later

    Installed by plasma-login-blur-slider; regenerated by
    "plasma-login-blur-slider sync". Do not edit.

    The wallpaper below is the unmodified stock plugin (stock/qmldir points at
    its real main.qml). This wrapper only adds the login-screen blur hook.
*/

import QtQuick
import "stock" as Stock
import "plmblur" as PlmBlur

Stock.StockMain {
    PlmBlur.LoginBlurHook {}
}
