/*
    SPDX-FileCopyrightText: 2026 Terry Fallows <terry@weion.dev>
    SPDX-License-Identifier: GPL-3.0-or-later

    Installed by plasma-login-blur-slider; regenerated by
    "plasma-login-blur-slider sync". Do not edit.

    The wallpaper below is the unmodified stock plugin (stock/qmldir points at
    its real main.qml). This wrapper only adds the login-screen blur hook.

    The hook is held in a property on purpose: declaring it as a child object
    would replace the stock wallpaper's own children (WallpaperItem uses
    "replace" semantics for list properties in derived components).
*/

import QtQuick
import "stock" as Stock
import "plmblur" as PlmBlur

Stock.StockMain {
    id: plasmaLoginBlurWrapper

    readonly property QtObject plasmaLoginBlurHook: PlmBlur.LoginBlurHook {
        wallpaperItem: plasmaLoginBlurWrapper
    }
}
